---

- name: Install Redis
  apt: name=redis-server state=latest
  sudo: yes

- name: Redis bind
  sudo: yes
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^#?bind\s*(.*)'
    line: "bind {{ private_ip }}"

- name: Redis in memory
  sudo: yes
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^save'
    state: absent

- name: Restart Redis
  sudo: yes
  service: name=redis-server state=restarted


