# --------------------------------------------------
# AWS keypair used to access the ec2 instances
keypair: bdelbosc

# Tag used to flag ec2 used for the bench
bench: b10b

# An s3 bucket for the binarystore
bucket: nuxeo-{{bench}}

# An s3 bucket used to save bench results
bucket_results: nuxeo-b10b-results


# The default Nuxeo distribution to use
#nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-distribution-tomcat-8.4-SNAPSHOT-nuxeo-cap.zip
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-server-tomcat-10.1-SNAPSHOT.zip

# AWS config
# ami-d37961b5 hvm:ebs-ssd 20170619 ubuntu 14.04
# ami-1c78607a hvm:ebs-io1 20170619 ubuntu 14.04
# ami-7a187c03 hvm:ebs-ssd 20180122 ubuntu 16.04
# ami-44455e22 nuxeo base on ami-58475f3e hvm:ebs 20170619 ubuntu 14.04 ffmeg broken
# ami-cc1473b5 nuxeo base on ami-7a187c03 hvm:ebs-ssd 20180122 ubuntu 16.04

aws_region: eu-west-1
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole
dbprofile: mongodb
amis:
  nuxeo: ami-cc1473b5
  mongodb: ami-7a187c03
  elastic: ami-7a187c03
  kafka: ami-7a187c03
  gatling: ami-7a187c03
  monitor: ami-7a187c03

# should we apt-get update && apt-get distupgrade ?
dist_upgrade: false

use_oracle_jdk: false
