# --------------------------------------------------
# AWS keypair used to access the ec2 instances
keypair: bdelbosc

# Tag used to flag ec2 used for the bench
bench: a500m

# Use EFS binary store
useEfsBinarystore: true

# Use an S3 binary store
useS3Binarystore: false

# The s3 bucket for the binary store
bucket: nuxeo-{{bench}}

# An s3 bucket used to save bench results
bucket_results: nuxeo-apl1b-results

# The default Nuxeo distribution to use
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-server-tomcat-10.2-SNAPSHOT.zip

# billing category
billing_category: presales
billing_subcategory: apple

# AWS config
# ami-d37961b5 hvm:ebs-ssd 20170619 ubuntu 14.04
# ami-1c78607a hvm:ebs-io1 20170619 ubuntu 14.04
# ami-7a187c03 hvm:ebs-ssd 20180122 ubuntu 16.04
# ami-44455e22 nuxeo base on ami-58475f3e hvm:ebs 20170619 ubuntu 14.04 ffmeg broken
# ami-cc1473b5 nuxeo base on ami-7a187c03 hvm:ebs-ssd 20180122 ubuntu 16.04

aws_region: eu-central-1
security_group: SUPINT-1029-sg
subnet_id: subnet-f686878e
instance_profile: SUPINT-1029-Role
dbprofile: mongodb
amis:
  nuxeo: ami-76643c9d
  nuxeospot: ami-76643c9d
  mongodb: ami-9515487e
  elastic: ami-9515487e
  kafka: ami-9515487e
  gatling: ami-9515487e
  monitor: ami-9515487e

# should we apt-get update && apt-get distupgrade ?
dist_upgrade: false

use_oracle_jdk: false
