---

- name: Check if diamond is setup
  stat:
    path: /etc/diamond/diamond.conf
  register: diamond_exists

- name: Get diamond deb package
  copy: src=diamond_4.0.468_all.deb dest=/tmp/diamond_4.0.468_all.deb force=no
  when: not diamond_exists.stat.exists

- name: Install diamond dep
  apt: name={{item}} state=latest
  with_items:
    - python-support
    - python-pymongo
    - python-redis

- name: Install package
  shell: dpkg -i /tmp/diamond_4.0.468_all.deb
  when: not diamond_exists.stat.exists

- name: Get hostname
  shell: hostname
  register: hostname

- name: Configure diamond
  template: src=diamond.conf.j2 dest=/etc/diamond/diamond.conf
  notify: Restart diamond
