---
# common task on all mongo server
# apt

- name: Add mongodb repo key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: Upgrade/install tools
  apt: state=latest name={{item}}
  with_items:
  - mongodb-org

# hugepage
- name: Disable hugepage defrag
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
