---
# common task on all mongo server
# apt

- name: Add mongodb repo key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

