---
# common task on all mongo server
# apt

- name: Add mongodb repo key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

