---
# Remove mongo

- name: "Stop mongo services"
  service: name={{item}} state=stopped enabled=no
  register: command_result
  failed_when: "command_result|failed and 'no service' not in command_result.msg"
  with_items:
  - mongos
  - mongocs
  - mongod

- name: "Remove config"
  command: rm -f /etc/init/mongocs.conf /etc/init/mongos.conf /etc/mongocs.conf

- name: "Remove data"
  command: rm -rf /ssd/mongod-data/ /ssd/mongocs/ /ssd/mongod-index /ssd/mongo-log