---
# mongod setup
- name: Check if mongod is already setup
  stat: path=/ssd/mongo-log/mongod.log
  register: std

- name: Install mongodb
  apt: state=latest name={{item}} force=yes
  with_items:
  - mongodb-org

- name: Set mongod configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod.conf

- name: Create mongod data dir
  file: path=/ssd/mongod-data state=directory owner=mongodb group=mongodb

- name: Create mongod index dir
  file: path=/ssd/mongod-index state=directory owner=mongodb group=mongodb

- name: Create mongo log dir
  file: path=/ssd/mongo-log state=directory owner=mongodb group=mongodb

- name: Link mongod index dir
  file: path=/ssd/mongod-data/index
        src=/ssd/mongod-index
        state=link
        force=yes

- name: Link mongod log
  file: path=/var/log/mongod.log
        src=/ssd/mongo-log/mongod.log
        state=link
        force=yes

- name: Restart mongod
  service: name=mongod state=restarted
  when: not std.stat.exists

- name: Ensure mongod started
  service: name=mongod state=started
  when: std.stat.exists
