---
# mongod setup

- name: Check if mongod is already setup
  stat: path=/ssd2/mongo-log/mongod.log
  register: std

- name: Set mongod configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod.conf

- name: Create mongod data dir
  file: path=/ssd1/mongod-data state=directory owner=mongodb group=mongodb

- name: Create mongod index dir
  file: path=/ssd2/mongod-index state=directory owner=mongodb group=mongodb

- name: Create mongo log dir
  file: path=/ssd2/mongo-log state=directory owner=mongodb group=mongodb

- name: Link mongod index dir
  file: path=/ssd1/mongod-data/index
        src=/ssd2/mongod-index
        state=link
        force=yes

- name: Link mongod log
  file: path=/var/log/mongod.log
        src=/ssd2/mongo-log/mongod.log
        state=link
        force=yes

# restart
- name: Restart mongod
  service: name=mongod state=restarted
  when: not std.stat.exists