---
# apt

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: Upgrade/install tools
  apt: state=latest name={{item}}
  with_items:
  - unzip
  - tree
  - atop
  - sysstat

- name: Activate sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: '^#?ENABLED\s*='
    line: "ENABLED=\"true\""

- name: Restart sysstat
  service: name=sysstat state=restarted

# TODO set /etc/hosts