---
- name: Gather ec2 facts
  action: ec2_facts

- name: Set pub and private ip
  set_fact:
    private_ip: "{{ansible_ec2_local_ipv4}}"
    public_ip: "{{ansible_ec2_public_ipv4}}"

#- name: Display all variables/facts known for a host
#  debug: var=hostvars[inventory_hostname] verbosity=4

# setup hosts and hostname
- name: Check if /etc/hosts is set
  stat: path=/etc/hosts.bak
  register: hostdone

- name: Setup hosts names
  include: ./set_hosts.yml
  when: not hostdone.stat.exists

# apt
- name: Update apt cache
  shell: apt-get update
  when: dist_upgrade and not hostdone.stat.exists

- name: Fix missing apt cache
  shell: apt-get update --fix-missing
  when: not hostdone.stat.exists

- name: Upgrade dist
  apt: upgrade=dist
  when: dist_upgrade and not hostdone.stat.exists

- name: Upgrade/install tools
  apt: state=latest name={{item}}
  with_items:
  - unzip
  - tree
  - atop
  - sysstat
  - xfsprogs
  - awscli
  - screen
  - mdadm
  when: not hostdone.stat.exists

- name: Activate sysstat
  lineinfile:
    dest: /etc/default/sysstat
    regexp: '^#?ENABLED\s*='
    line: "ENABLED=\"true\""

- name: Change sysstat frequency
  lineinfile:
    dest: /etc/cron.d/sysstat
    regexp: 'debian-sa1 1 1$'
    line: "*/2 * * * * root command -v debian-sa1 > /dev/null && debian-sa1 1 1"
  notify: Restart sysstat

- name: Change atop frequency
  lineinfile:
    dest: /etc/default/atop
    regexp: '^INTERVAL='
    line: "INTERVAL=120"
  notify: Restart atop

- include: disk_layout_nvme.yml

- name: Disable unattendy update
  lineinfile:
    dest: /etc/apt/apt.conf.d/10periodic
    regexp: '^#?APT..Periodic..Unattended.Upgrade'
    line: "APT::Periodic::Unattended-Upgrade \"0\";"
