---
# install mongoc config server
- name: Set mongocs configuration file
  template: src=mongocs.conf.j2 dest=/etc/mongocs.conf

- name: Set mongocs upstart file
  template: src=mongocs.j2 dest=/etc/init/mongocs.conf

- name: Create mongocs dir
  file: path=/ssd1/mongocs state=directory owner=mongodb group=mongodb

# restart
- name: Restart mongocs
  service: name=mongocs state=restarted

- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Pause for a while
  pause: seconds=20

- name: Initialize the replication set
  shell: /usr/bin/mongo --port "27018" /tmp/repset_init.js