---

- name: Add Docker repository key
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Alternative | Add Docker repository key
  shell: "curl -sSL hkp://p80.pool.sks-keyservers.net:80 | sudo apt-key add -"
  when: add_repository_key|failed

- name: HTTPS APT transport for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    mode: '644'
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: "docker-engine"
    state: "latest"
    update_cache: yes
    cache_valid_time: "600"

# We must install pip via apt before we can use the pip module below
- name: Install pip, python-dev package with apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: "600"
  with_items:
    - python-dev
    - python-pip

# Upgrade pip with pip to fix angstwad/docker.ubuntu/pull/35 and docker-py/issues/525
# Install latest version when no specific release is set.
- name: Upgrade latest pip, setuptools, docker and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: pip }
    - { name: setuptools }
    - { name: docker }
    - { name: docker-compose }
  ignore_errors: yes

- name: Check if /etc/updatedb.conf exists
  stat:
    path: /etc/updatedb.conf
  register: updatedb_conf_exists

- name: Ensure updatedb does not index docker
  lineinfile:
    dest: /etc/updatedb.conf
    state: present
    backrefs: yes
    regexp: '^PRUNEPATHS="(/ssd1/docker )?(.*)"$'
    line: 'PRUNEPATHS="/ssd1/docker \2"'
  when: updatedb_conf_exists.stat.exists

- name: Check if /etc/default/ufw exists
  stat:
    path: /etc/default/ufw
  register: ufw_default_exists

- name: Change ufw default forward policy from drop to accept
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""
  when: ufw_default_exists.stat.exists

- name: Change docker root
  lineinfile:
    dest: /etc/default/docker
    regexp: "^#?DOCKER_OPTS="
    line: "DOCKER_OPTS=\"-g /ssd1/docker\""
    #line: "DOCKER_OPTS=\"-dns 8.8.8.8 -dns 8.8.4.4 -g /ssd1/docker\""
  when: ufw_default_exists.stat.exists

- name: Stop docker
  service:
    name: docker
    state: stopped

- name: Move docker
  shell: mv /var/lib/docker /ssd1/docker

- name: Start docker
  service:
    name: docker
    state: started
