---
- include: disk_layout.yml

- name: Check if docker is setup
  stat:
    path: /etc/default/docker
  register: docker_default_exists

- name: Install docker
  include: docker.yml
  when: not docker_default_exists.stat.exists

- name: Add screen conf
  copy: src=screenrc dest=/home/ubuntu/.screenrc owner=ubuntu force=no

- name: Add docker files
  copy: src=monitor dest=/ssd1/ force=no

- name: Start docker compose
  shell: docker-compose up -d
  args:
    chdir: /ssd1/monitor

