---

# setup nuxeo conf
- name: Config - Zookeeper
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?kafka.zkServers\s*(.*)'
    line: "kafka.zkServers={% for host in groups['kafka'] -%}{{ hostvars[host]['private_ip'] }}:2181{%- if not loop.last %},{% endif -%}{%- endfor %}"

- name: Config - Kafka brokers
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?kafka.zkServers\s*(.*)'
    line: "kafka.bootstrap.servers={% for host in groups['kafka'] -%}{{ hostvars[host]['private_ip'] }}:9092{%- if not loop.last %},{% endif -%}{%- endfor %}"

- name: Config - Kafka and Workmanager templates
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?nuxeo\.templates\s*='
    line: "nuxeo.templates=kafka,mqueues-workmanager,default,mongodb,perf,b10b"
