---

# setup nuxeo conf
- name: Config - Activate kafka
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?kafka.enabled\s*(.*)'
    line: "kafka.enabled=true"

- name: Config - Zookeeper
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?kafka.zkServers\s*(.*)'
    line: "kafka.zkServers={% for host in groups['kafka'] -%}{{ hostvars[host]['private_ip'] }}:2181{%- if not loop.last %},{% endif -%}{%- endfor %}"

- name: Config - Kafka brokers
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?kafka.bootstrap.servers\s*(.*)'
    line: "kafka.bootstrap.servers={% for host in groups['kafka'] -%}{{ hostvars[host]['private_ip'] }}:9092{%- if not loop.last %},{% endif -%}{%- endfor %}"

- name: Config - Kafka over provisionning
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?nuxeo.stream.work.over.provisioning.factor\s*(.*)'
    line: "nuxeo.stream.work.over.provisioning.factor=4"

- name: Config - Kafka Stream WorkManager
  lineinfile:
    dest: /opt/nuxeo/conf/nuxeo.conf
    regexp: '^#?nuxeo.stream.work.enabled\s*(.*)'
    line: "nuxeo.stream.work.enabled=true"

