---
- name: Set facts
  set_fact:
    nbBlobsPerNode: "{{ (impnbBlobs/counts.nuxeo/impnbThreads)|int}}"
    nbDocumentsPerNode: "{{( impnbNodes/counts.nuxeo/impnbThreads)|int }}"
    blobInfos: "/ssd/nuxeo-data/import/blob-infos"
    mqueuesBatchThresholdS: "45"
  tags:
  - continue

- name: Create blob info directory
  file: path="{{blobInfos}}" state=directory owner=nuxeo

- name: Notify graphite generating blobs
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Generating blobs", "tags":"phases import", "data": "From {{inventory_hostname}} nbThreads={{impnbThreads}} nbBlobs={{nbBlobsPerNode}}"}'''
- name: Generating blobs
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runRandomBlobProducers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest''  -d ''{"params":{"nbBlobs": {{nbBlobsPerNode}}, "nbThreads": {{impnbThreads}}, "avgBlobSizeKB": {{impBlobsSizeKB}}, "mqName": "import-blobs", "kafkaConfig": "default"} }'''

- name: Notify graphite importing blobs
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Import blobs", "tags":"phases import", "data": "From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}} nbBlobs={{nbBlobsPerNode}}"}'''
- name: Uploading blobs into binarystore
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runBlobConsumers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"blobProviderName": "default", "blobInfoPath": "{{blobInfos}}", "mqName": "import-blobs", "kafkaConfig": "default"}}'''

- name: Notify graphite generating documents
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Generating documents", "tags":"phases import", "data": "From {{inventory_hostname}} nbThreads={{impnbThreads}} nbNodes={{nbDocumentsPerNode}}"}'''
- name: Generating documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runRandomDocumentProducers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"nbDocuments": {{nbDocumentsPerNode}}, "nbThreads": {{impnbThreads}}, "blobInfoPath": "{{blobInfos}}", "mqName": "import-documents", "kafkaConfig": "default" }}'''

- name: Notify graphtie importing doucments
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Importing documents", "tags":"phases import", "data": "From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}} nbNodes={{nbDocumentsPerNode}}"}'''
  tags:
  - continue
- name: Import documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runDocumentConsumers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"rootFolder": "/default-domain/workspaces", "mqName": "import-documents", "kafkaConfig": "default", "batchThresholdS": "{{mqueuesBatchThresholdS}}", "batchSize": {{impbatchSize}}}}'''
  tags:
  - continue
