---
- name: Send graphite event to notify import start
  shell:  'curl -XPOST http://monitor1/events/  -d ''{"what": "Start import", "tags":"phases import", "data": "From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}} nbNodes={{impnbNodes}}"}'''

- name: Run importer
  shell: curl -XGET -vv -u Administrator:Administrator "http://127.0.0.1:8080/nuxeo/site/randomImporter/run?targetPath=/default-domain/workspaces&batchSize={{impbatchSize}}&nbThreads={{impnbThreads}}&interactive=false&nbNodes={{impnbNodes}}&fileSizeKB=0&bulkMode=true&onlyText=false&withProperties=true&blockAsyncProcessing=true&blockSyncPostCommitProcessing=true"

