---
- name: Step 4 - Set facts
  set_fact:
    mqueuesBatchThresholdS: "45"

- name: Step 4 - Notify graphtie importing doucments
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Importing documents", "tags":"phases import", "data": "Step 4 - From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}}"}'''
- name: Step 4 - Import documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runDocumentConsumers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"rootFolder": "/default-domain/workspaces", "mqName": "import-documents", "kafkaConfig": "default", "batchThresholdS": "{{mqueuesBatchThresholdS}}", "batchSize": {{impbatchSize}}}}'''
