---
- name: Set facts
  set_fact:
    nbBlobsPerNode: "{{ (impnbBlobs/counts.nuxeo/impnbThreads)|int}}"
    nbDocumentsPerNode: "{{( impnbNodes/counts.nuxeo/impnbThreads)|int }}"
    blobInfos: "/ssd2/nuxeo-data/import/blob-infos"
    mqueuesBlob: "/ssd2/nuxeo-data/import/mqueues-blob"
    mqueuesDoc: "/ssd2/nuxeo-data/import/mqueues-doc"

- name: Create blob info directory
  file: path="{{blobInfos}}" state=directory owner=nuxeo

- name: Notify graphite generating blobs
  shell:  'curl -XPOST http://monitor1/events/  -d ''{"what": "Generating blobs", "tags":"phases import", "data": "From {{inventory_hostname}} nbThreads={{impnbThreads}} nbBlobs={{nbBlobsPerNode}}"}'''

- name: Generating blobs
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runRandomBlobProducers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest''  -d ''{"params":{"nbBlobs": {{nbBlobsPerNode}}, "nbThreads": {{impnbThreads}}, "queuePath": "{{mqueuesBlob}}"} }'''

- name: Notify graphite importing blobs
  shell:  'curl -XPOST http://monitor1/events/  -d ''{"what": "Import blobs", "tags":"phases import", "data": "From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}} nbBlobs={{nbBlobsPerNode}}"}'''

- name: Uploading blobs into binarystore
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runBlobConsumers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"blobProviderName": "default", "blobInfoPath": "{{blobInfos}}", "queuePath": "{{mqueuesBlob}}"}}'''

- name: Notify graphite generating documents
  shell:  'curl -XPOST http://monitor1/events/  -d ''{"what": "Start import", "tags":"phases import", "data": "From {{inventory_hostname}} nbThreads={{impnbThreads}} nbNodes={{nbDocumentsPerNode}}"}'''

- name: Generating documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runRandomDocumentProducers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"nbDocuments": {{nbDocumentsPerNode}}, "nbThreads": {{impnbThreads}}, "blobInfoPath": "{{blobInfos}}",  "queuePath": "{{mqueuesDoc}}"}}'''

- name: Notify graphtie importing doucments
  shell:  'curl -XPOST http://monitor1/events/  -d ''{"what": "Start import", "tags":"phases import", "data": "From {{inventory_hostname}} batchSize={{impbatchSize}} nbThreads={{impnbThreads}} nbNodes={{nbDocumentsPerNode}}"}'''

- name: Import documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runDocumentConsumers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"rootFolder": "/default-domain/workspaces", "queuePath": "{{mqueuesDoc}}", "batchSize": {{impbatchSize}}}}'''

