---
- name: Step 3 - Set facts
  set_fact:
    nbDocumentsPerNode: "{{( impnbNodes/counts.nuxeo/impnbThreads)|int }}"
    mqSize: "{{ (counts.nuxeo*impnbThreads)|int }}"
    pause: "{{ 10 | random }}"
  tags:
  - continue

- name: Step 3 - Random pause to prevent conflict in queue creation
  shell: 'sleep {{pause}}'

- name: Step 3 - Notify graphite generating documents
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Generating documents", "tags":"phases import", "data": "Step 3 - From {{inventory_hostname}} nbThreads={{impnbThreads}} nbNodes={{nbDocumentsPerNode}}"}'''

- name: Step 3 - Generating documents
  shell: 'curl -X POST ''http://localhost:8080/nuxeo/site/automation/MQImporter.runRandomDocumentProducers'' -u Administrator:Administrator -H ''content-type: application/json+nxrequest'' -d ''{"params":{"nbDocuments": {{nbDocumentsPerNode}}, "nbThreads": {{impnbThreads}}, "mqBlobInfo": "import-blobs-info", "mqName": "import-documents", "mqSize": {{mqSize}}, "kafkaConfig": "default" }}'''
