---
- name: Run imdexing
  run_once: true
  shell: curl -XPOST -u Administrator:Administrator -H "Content-Type:application/json+nxrequest" -d '{"params":{},"context":{}}' "http://localhost:8080/nuxeo/site/automation/Elasticsearch.Index"

