---

- name: Send graphite event to notify indexing start
  run_once: true
  shell:  'curl -XPOST http://monitor1:8080/events/  -d ''{"what": "Indexing", "tags":"phases index", "data": "From {{inventory_hostname}}"}'''

- name: Run imdexing
  run_once: true
  shell: curl -XPOST -u Administrator:Administrator -H "Content-Type:application/json+nxrequest" -d '{"params":{},"context":{}}' "http://localhost:8080/nuxeo/site/automation/Elasticsearch.Index"

