---
aws_region: eu-west-1
bench: b10bbis
#keypair: Jenkins
keypair: bdelbosc
dbprofile: mongodb
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole

amis:
  mongodb: ami-1e4cd86d
  nuxeo: ami-910fa9e2
types:
  mongodb: c3.large
  nuxeo: c3.large
counts:
  mongodb: 3
  nuxeo: 1
