---
# AWS keypair used to access the ec2 instances
#keypair: Jenkins
keypair: bdelbosc

# --------------------------------------------------
# 1B target

#### Type of ec2
#types:
#  mongodb: m4.4xlarge
#  nuxeo: c4.2xlarge
#  elastic: m4.4xlarge
#  gatling: c4.2xlarge
#  monitor: c4.xlarge
#
#counts:
#  mongodb: 2
#  nuxeo: 2
#  elastic: 2
#  gatling: 1
#  monitor: 1
#
## ebs volume size per disk per instance: total size for a group is: counts * volsizes * raid0
#volsizes:
#  mongodb: 125  # 1t: 2*4*125, 10kIOPS
#  nuxeo: 200    # 800g: 2*2*200
#  elastic: 180  # 1.44t: 2*4*180, 10kIOPS
#  gatling: 30   # 30g
#  monitor: 30   # 60g: 1*2*30
#
#voltypes:
#  mongodb: io1
#  nuxeo: gp2
#  elastic: io1
#  gatling: gp2
#  monitor: gp2
#
#raid0:
#  mongodb: 4
#  nuxeo: 2
#  elastic: 4
#  gatling: 0
#  monitor: 2
#
## provisioned iops for io1 ebs disk, limited to 40k iops per region
#iops: 1250
#
## Mass Import configuration
#impnbThreads: 128
#impbatchSize: 64
#impnbNodes:  1000000000
#impnbBlobs:    10000000
#impBlobsSizeKB: 1


# --------------------------------------------------
# 100m target testing

# Type of ec2 to use for testing
types:
  mongodb: m4.xlarge
  nuxeo: c4.2xlarge
  elastic: c4.2xlarge
  gatling: c4.2xlarge
  kafka: c4.xlarge
  monitor: c4.xlarge

# Number of nodes
#counts:

counts:
  mongodb: 4
  nuxeo: 3
  elastic: 3
  gatling: 1
  kafka: 1
  monitor: 1

# ebs volume size per disk per instance: total size for a group is: counts * volsizes * raid0
volsizes:
  mongodb: 25
  nuxeo: 125
  elastic: 40
  gatling: 40
  kafka: 300
  monitor: 20

voltypes:
  mongodb: io1
  elastic: io1
  nuxeo: gp2
  gatling: gp2
  kafka: gp2
  monitor: gp2

# number of ebs disk to aggregate in raid0
raid0:
  mongodb: 4
  nuxeo: 2
  elastic: 4
  gatling: 0
  kafka: 2
  monitor: 2

#iops: 2000
iops: 100

# Mass Import configuration with nuxeo-platform-importer
#impnbThreads: 90
#impbatchSize: 200
#impnbNodes:  100000000
#impnbBlobs:    100000
#impBlobsSizeKB: 1

impnbThreads: 20
impbatchSize: 20
impnbNodes:  10000000
impnbBlobs:    1000
impBlobsSizeKB: 1

# --------------------------------------------------
# Tag used to flag ec2 used for the bench
bench: b10b

# An s3 bucket for the binarystore
bucket: nuxeo-{{bench}}

# An s3 bucket used to save bench results
bucket_results: nuxeo-b10b-results


# The default Nuxeo distribution to use
#nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-distribution-tomcat-8.4-SNAPSHOT-nuxeo-cap.zip
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-server-tomcat-9.2-SNAPSHOT.zip

# AWS config
# ami-d37961b5 hvm:ebs-ssd 20170619 ubuntu 14.04
# ami-1c78607a hvm:ebs-io1 20170619 ubuntu 14.04
# ami-44455e22 nuxeo base on ami-58475f3e hvm:ebs 20170619 ubuntu 14.04

aws_region: eu-west-1
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole
dbprofile: mongodb
amis:
  nuxeo: ami-44455e22
  mongodb: ami-1c78607a
  elastic: ami-1c78607a
  kafka: ami-d37961b5
  gatling: ami-d37961b5
  monitor: ami-d37961b5

# should we apt-get update && apt-get distupgrade ?
dist_upgrade: false