---
#keypair: Jenkins
keypair: bdelbosc
bench: b10b
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-distribution-tomcat-8.3-SNAPSHOT-nuxeo-cap.zip

impnbThreads: 100
impbatchSize: 200
impnbNodes: 25000000

aws_region: eu-west-1
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole
dbprofile: mongodb
amis:
  mongodb: ami-1e4cd86d
  nuxeo: ami-910fa9e2
types:
  mongodb: c3.xlarge
  nuxeo: c3.xlarge
#  mongodb: c3.4xlarge
#  nuxeo: c3.4xlarge
counts:
  mongodb: 2
  nuxeo: 1
