---
# AWS keypair used to access the ec2 instances
#keypair: Jenkins
keypair: bdelbosc

# Type of ec2 to use for 1b
types:
  mongodb: m3.xlarge
  nuxeo: c3.4xlarge
  elastic: i2.2xlarge
  gatling: c3.2xlarge
  monitor: c3.xlarge

# Type of ec2 to use for testing
#types:
#  mongodb: m3.xlarge
#  nuxeo: c3.2xlarge
#  elastic: c3.2xlarge
#  gatling: c3.2xlarge
#  monitor: c3.xlarge


# Number of nodes
counts:
  mongodb: 7
  nuxeo: 2
  elastic: 3
  gatling: 1
  monitor: 1

# An s3 bucket used to save bench results
bucket_results: nuxeo-b10b-results

# Tag used to flag ec2 used for the bench
bench: b10b

# The default Nuxeo distribution to use
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-distribution-tomcat-8.4-SNAPSHOT-nuxeo-cap.zip

# Mass Import configuration
impnbThreads: 90
impbatchSize: 100
impnbNodes: 500000000

# AWS config
aws_region: eu-west-1
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole
dbprofile: mongodb
amis:
  nuxeo: ami-910fa9e2
  mongodb: ami-55452e26
  elastic: ami-55452e26
  gatling: ami-55452e26
  monitor: ami-55452e26

# should we apt-get update && apt-get distupgrade ?
dist_upgrade: false