---
# AWS keypair used to access the ec2 instances
#keypair: Jenkins
keypair: bdelbosc

# --------------------------------------------------
# 1B target

## Type of ec2
types:
  mongodb: m3.xlarge
  nuxeo: c3.4xlarge
  elastic: c3.4xlarge
  gatling: c3.2xlarge
  monitor: c3.xlarge

counts:
  mongodb: 7
  nuxeo: 2
  elastic: 4
  gatling: 1
  monitor: 1

# additional ebs volume
volsizes:
  mongodb: 100
  nuxeo: 500 # this is for mqueues 1b docs = 800g (400g per node for 2 nodes)
  elastic: 1
  gatling: 1
  monitor: 1

# Mass Import configuration
impnbThreads: 128
impbatchSize: 200
impnbNodes:  1000000000
impnbBlobs:    10000000
impBlobsSizeKB: 1


# --------------------------------------------------
# 100m target testing

## Type of ec2 to use for testing
#types:
#  mongodb: m3.xlarge
#  nuxeo: c3.2xlarge
#  elastic: c3.2xlarge
#  gatling: c3.2xlarge
#  monitor: c3.xlarge
#
## Number of nodes
#counts:
#  mongodb: 4
#  nuxeo: 2
#  elastic: 3
#  gatling: 1
#  monitor: 1
#
## additional ebs volume
#volsizes:
#  mongodb: 100
#  nuxeo: 200 # this is for mqueues 1b docs = 800g (400g per node for 2 nodes)
#  elastic: 1
#  gatling: 1
#  monitor: 1
#
## Mass Import configuration with nuxeo-platform-importer
#impnbThreads: 90
#impbatchSize: 200
#impnbNodes:  100000000
#impnbBlobs:    100000
#impBlobsSizeKB: 1

# --------------------------------------------------
# Tag used to flag ec2 used for the bench
bench: b10b

# An s3 bucket for the binarystore
bucket: nuxeo-{{bench}}

# An s3 bucket used to save bench results
bucket_results: nuxeo-b10b-results


# The default Nuxeo distribution to use
#nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-distribution-tomcat-8.4-SNAPSHOT-nuxeo-cap.zip
nuxeo_distribution: http://community.nuxeo.com/static/snapshots/nuxeo-server-tomcat-9.1-SNAPSHOT.zip

# AWS config
aws_region: eu-west-1
security_group: jenkins-vpc
subnet_id: subnet-dbac2a82
instance_profile: JenkinsRole
dbprofile: mongodb
amis:
  nuxeo: ami-910fa9e2
  mongodb: ami-55452e26
  elastic: ami-55452e26
  gatling: ami-55452e26
  monitor: ami-55452e26

# should we apt-get update && apt-get distupgrade ?
dist_upgrade: false