---
# --------------------------------------------------
# b10m custom config for DAM

# Type of ec2 to use for testing
types:
  mongodb: m4.2xlarge
  nuxeo: c4.4xlarge
  elastic: c4.4xlarge
  gatling: c4.2xlarge
  kafka: c4.xlarge
  monitor: c4.xlarge

# Number of nodes
counts:
  mongodb: 2
  nuxeo: 2
  elastic: 1
  gatling: 1
  kafka: 1
  monitor: 1

# ebs volume size per disk per instance: total size for a group is: counts * volsizes * raid0
volsizes:
  mongodb: 50  # 100g per node -> 200g total
  nuxeo: 50    # 100g per node -> 200g total
  elastic: 100 # 200g per node -> 200g total
  kafka: 50    # 100g per node -> 100g total
  gatling: 40
  monitor: 20

voltypes:
  mongodb: io1
  elastic: io1
  nuxeo: io1
  gatling: gp2
  kafka: gp2
  monitor: gp2

# number of ebs disk to aggregate in raid0
raid0:
  mongodb: 2
  nuxeo: 2
  elastic: 2
  gatling: 0
  kafka: 2
  monitor: 2

#iops: 2000
iops: 500

# Mass Import configuration with nuxeo-platform-importer
impnbThreads: 20
impnbNodes:  10000000
impnbBlobs:     10000
impBlobsSizeKB:  1
impbatchSize: 10

# Test
#impnbThreads: 2
#impnbNodes:  500
#impnbBlobs:    100
#impBlobsSizeKB: 1
#impbatchSize: 10
