---
- hosts: kafka
  gather_facts: no
  user: ubuntu
  sudo: yes
  tasks:
  - name: Stop kafka
    service: name=kafkad state=stopped
  - name: Stop zookeeper
    service: name=zookeeper state=stopped
  - name: Reset Data
    include: ../roles/kafka/tasks/reset_data.yml
  - name: Start zookeeper
    service: name=zookeeper state=started
  - name: Start kafka
    service: name=kafkad state=started
