---
- hosts: localhost
  gather_facts: no
  tasks:
  - include: ../roles/ec2/tasks/resume.yml

- hosts: elastic
  gather_facts: no
  sudo: yes
  tasks:
  - name: Start elasticsearch
    service: name=elasticsearch state=started

