---
- hosts: kafka
  gather_facts: no
  sudo: yes
  tasks:
  - name: Wake up kafka
    service: name=kafkad state=started

- hosts: monitor
  gather_facts: no
  sudo: yes
  tasks:
  - name: Start docker compose
    shell: docker-compose up -d
    args:
      chdir: /ssd/monitor

- hosts: nuxeo:mongodb:kafka:elastic:gatling
  gather_facts: no
  sudo: yes
  tasks:
  - name: Wake up diamond
    service: name=diamond state=started

- hosts: mongodb
  gather_facts: no
  sudo: yes
  tasks:
  - name: Wake up mongod
    service: name=mongod state=started
  - name: Wake up mongocs
    service: name=mongocs state=started

- hosts: nuxeo
  gather_facts: no
  sudo: yes
  tasks:
  - name: Wake up mongos
    service: name=mongos state=started

- hosts: elastic
  gather_facts: no
  sudo: yes
  tasks:
  - name: Wake up elastic
    service: name=elasticsearch state=started
