---
# apt

- name: Add mongodb repo key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: Upgrade/install tools
  apt: state=latest name={{item}}
  with_items:
  - xfsprogs
  - mongodb-org

# disk
- name: Umount /mnt
  mount: name=/mnt src=/dev/xvdb fstype=ext4 state=absent

# ssd1
- name: Check if ssd1 volume is mounted
  shell: cat /proc/mounts | grep /dev/xvdb
  changed_when: False
  failed_when: False
  register: mounted

- name: Format ssd1 volume
  shell: mkfs.xfs -f /dev/xvdb
  when: mounted.stdout == ""

- name: Mount /ssd1
  mount: name=/ssd1 fstype=xfs src=/dev/xvdb opts=noatime,nodiratime state=mounted
  when: mounted.stdout == ""

- name: Set ssd1 read ahead
  # 32 sector is 16k
  shell: blockdev --setra 32 /dev/xvdb
  when: mounted.stdout == ""

- name: Use noop scheduler ssd1
  shell: echo noop > /sys/block/xvdb/queue/scheduler
  when: mounted.stdout == ""

# ssd2
- name: Check if ssd2 volume is mounted
  shell: cat /proc/mounts | grep /dev/xvdc
  changed_when: False
  failed_when: False
  register: mounted

- name: Format ssd2 volume
  shell: mkfs.xfs -f /dev/xvdc
  when: mounted.stdout == ""

- name: Mount /ssd2
  mount: name=/ssd2 fstype=xfs src=/dev/xvdc opts=noatime,nodiratime state=mounted
  when: mounted.stdout == ""

- name: Set ssd2 read ahead
  # 32 sector is 16k
  shell: blockdev --setra 32 /dev/xvdc
  when: mounted.stdout == ""

- name: Use noop scheduler ssd2
  shell: echo noop > /sys/block/xvdc/queue/scheduler
  when: mounted.stdout == ""

# hugepage
- name: Disable hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled
  when: mounted.stdout == ""

# mongodb setup

- name: Set mongo configuration file
  template: src=mongod.j2 dest=/etc/mongod.conf

- name: Create mongodb data dir
  file: path=/ssd1/mongodb-data state=directory owner=mongodb group=mongodb

- name: Create mongodb index dir
  file: path=/ssd2/mongodb-index state=directory owner=mongodb group=mongodb

- name: Create mongodb index dir
  file: path=/ssd2/mongodb-log state=directory owner=mongodb group=mongodb

- name: Link mongodb index dir
  file: path=/ssd1/mongodb-data/index
        src=/ssd2/mongodb-index
        state=link
        force=yes

# restart
- name: Restart mongod
  service: name=mongod state=restarted