---
- name: List stopped instances
  shell: aws ec2 describe-instances --filters "Name=tag:bench,Values={{bench}}" "Name=instance-state-name,Values=stopped" --region={{aws_region}} --no-paginate --query "Reservations[*].Instances[*].InstanceId" | grep "i-" | tr -d '" ,' | paste -d, -s
  changed_when: False
  register: existing_instances

- name: Start stopped instances
  ec2:
    region: "{{aws_region}}"
    instance_ids: "{{existing_instances.stdout}}"
    state: "running"
    wait: yes
  register: started_instances
  when: existing_instances.stdout != ""

- name: "Wait for SSH to be available on all instances"
  wait_for:
    host: "{{ item.private_ip if keypair == 'Jenkins' else item.public_ip }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
  with_items: "{{ started_instances.instances }}"
  when: existing_instances.stdout != ""
