FROM hopsoft/graphite-statsd

ADD 10_fix_carbon_conf.sh /etc/my_init.d/10_fix_carbon_conf.sh
ADD 20_fix_graphite_conf.sh /etc/my_init.d/20_fix_graphite_conf.sh

ADD graphTemplates.conf /opt/graphite/conf/graphTemplates.conf

