---
# install java 8
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8 and other tools
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    - git
    - ant
    - redis-server
    - pound

# install maven
- name: Check if maven is already installed
  stat: path=/opt/maven3/bin/mvn
  register: stmvn

- name: Download Apache Maven
  get_url: url=http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/tmp/apache-maven-3.3.9.tar.gz
  when: not stmvn.stat.exists

- name: Untar Maven
  shell: chdir=/tmp creates=/opt/apache-maven-3.3.9 tar -zxf apache-maven-3.3.9.tar.gz -C /opt
  when: not stmvn.stat.exists

- name: Untar Maven
  shell: mv /opt/apache-maven-3.3.9 /opt/maven3
  when: not stmvn.stat.exists


# setup pound
- name: Setup pound load balancer
  template: src=pound.cfg.j2 dest=/etc/pound/pound.cfg

- name: Enable pound
  lineinfile:
    dest: /etc/default/pound
    regexp: '^#?startup=\s*(.*)'
    line: "startup=1"

- name: Restart pound
  shell: service pound restart

- name: Get the bench tag
  set_fact: stamp_tag="{{ hostvars[groups['nuxeo'][0]]['bench_tag'] }}"

# Setup bench script
- name: Setup the bench script
  template: src=run_bench.sh dest=/home/ubuntu/run_bench.sh mode=0755 owner=ubuntu force=yes

- name: Add moustache
  copy: src=data.mustache dest=/home/ubuntu/data.mustache owner=ubuntu force=yes

- name: Add screen conf
  copy: src=screenrc dest=/home/ubuntu/.screenrc owner=ubuntu force=no


