  ---
- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  become: yes
  tasks:
  # Stop it's up - we don't want it connected
  # to other resources when we reset those
  - name: Check for nuxeoctl wrapper
    stat: path=/usr/bin/nuxeoctl
    register: nuxeoctl
  - name: Stop nuxeo
    shell: nuxeoctl stop
    when: nuxeoctl.stat.exists
    failed_when: False

- hosts: mongodb
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - reset_mongodb

- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - reset_nuxeo

- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  become: yes
  serial: 1
  roles:
  - start_nuxeo
