---
# init the benchmark instances needed to run the import phase: only nuxeo and mongo servers are required
- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: mongodb}
  - {role: ec2, type: nuxeo}

- hosts: mongodb:nuxeo
  gather_facts: no
  sudo: yes
  roles:
  - role: common
  - role: mongo_common

- hosts: mongodb
  gather_facts: no
  sudo: yes
  pre_tasks:
  - include: ./roles/mongo_common/tasks/disk_layout.yml
  roles:
  - role: mongo_config_server
  - role: mongo_db
#  - role: mongo_router

- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: nuxeo
  - role: mongo_router