---
# init the benchmark instances needed to run the import phase: only nuxeo and mongo servers are required
- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - role: s3
# efs need to be created by hand
#  - role: efs
  - {role: ec2, type: monitor}
  - {role: ec2, type: kafka}
  - {role: ec2, type: mongodb}
  - {role: ec2, type: nuxeo}

- hosts: kafka:mongodb:nuxeo:monitor
  gather_facts: no
  sudo: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: kafka:mongodb:nuxeo:monitor
  gather_facts: no
  sudo: yes
  roles:
  - role: common

- hosts: monitor
  gather_facts: no
  sudo: yes
  roles:
  - role: monitor
  - role: diamond

- hosts: kafka
  gather_facts: no
  sudo: yes
  roles:
  - role: kafka
  - role: diamond

- hosts: mongodb
  gather_facts: no
  sudo: yes
  roles:
  - role: mongo_common
  - role: mongo_config_server
  - role: mongo_db
  - role: diamond

- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  sudo: yes
  roles:
  - role: mongo_common
  - role: mongo_router
  - role: nuxeo
  - role: diamond
  - role: flame
  tasks:
  - include: ./roles/nuxeo/tasks/config_graphite.yml

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Summary
    debug: msg="Monitoring {{groups.monitor.0}}   Nuxeo {{groups.nuxeo}}   Mongo {{groups.mongodb}}  Kafka {{groups.kafka}}"

