---
- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: mongodb}
  - {role: ec2, type: nuxeo}

- hosts: all
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: common

- hosts: mongodb
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: mongo_common

- hosts: mongodb
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: mongo_config_server

- hosts: mongodb
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: mongo_db

- hosts: mongodb
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: mongo_router

- hosts: nuxeo
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: nuxeo