---
# init the gatling server

- hosts: localhost
  gather_facts: no
  sudo: no
  tasks:
    - name: Get a bench tag
      shell: echo "$(date +%y%m%d-%H%M)_{{counts.mongodb}}mongo-as-{{types.mongodb}}_{{counts.nuxeo}}nuxeo-as-{{types.nuxeo}}"
      register: stamp_tag

- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: gatling}

- hosts: gatling
  gather_facts: no
  user: ubuntu
  become: yes
  roles:
  - role: common
  - role: gatling
