---
# init the elasticsearch infra needed to run indexing

- hosts: nuxeo
  gather_facts: no
  sudo: yes
  tasks:
  - include: ./roles/nuxeo/tasks/stop.yml

- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: elastic}

- hosts: elastic
  gather_facts: no
  sudo: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: elastic
  gather_facts: no
  sudo: yes
  roles:
  - role: common
  - role: elastic
  - role: diamond
  - role: flame

- hosts: nuxeo
  gather_facts: no
  sudo: yes
  serial: 1
  roles:
  - redis
  tasks:
  - include: ./roles/nuxeo/tasks/config_elastic.yml
  - include: ./roles/nuxeo/tasks/start.yml

# reconfigure diamond to monitor elastic and redis
- hosts: monitor
  gather_facts: no
  sudo: yes
  roles:
  - role: diamond
