---
# init the gatling server

- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: gatling}

- hosts: gatling
  gather_facts: no
  sudo: yes
  roles:
  - role: common
  - role: gatling
  - role: diamond

