---
# init the monitoring server

- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: monitor}

- hosts: monitor
  gather_facts: no
  sudo: yes
  roles:
  - role: common
  - role: monitor
