---
# init the elasticsearch infra needed to run indexing

- hosts: nuxeo
  gather_facts: no
  sudo: yes
  tasks:
  - include: ./roles/nuxeo/tasks/stop.yml

- hosts: localhost
  gather_facts: no
  sudo: no
  pre_tasks:
    - name: Get the bench tag
      shell: echo "{{ hostvars[groups['nuxeo'][0]]['bench_tag'] }}"
      register: stamp_tag
  roles:
  - {role: ec2, type: nuxeo}
  - {role: ec2, type: elastic}

- hosts: elastic
  gather_facts: no
  sudo: yes
  roles:
  - role: common
  - role: elastic

- hosts: nuxeo
  gather_facts: no
  sudo: yes
  serial: 1
  tasks:
  - include: ./roles/nuxeo/tasks/config_elastic.yml
  - include: ./roles/nuxeo/tasks/start.yml
