---
# init the elasticsearch infra needed to run indexing

- hosts: localhost
  gather_facts: no
  sudo: no
  roles:
  - {role: ec2, type: nuxeospot}

- hosts: nuxeospot
  gather_facts: no
  sudo: yes
  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
  - role: common
  - role: mongo_common
  - role: mongo_router
  - role: nuxeo
  - role: diamond
  - role: flame
  post_tasks:
  - include: ./roles/nuxeo/tasks/config_graphite.yml
  - include: ./roles/nuxeo/tasks/config_async.yml
  - include: ./roles/nuxeo/tasks/start.yml
