---
# --------------------------------------------------
# b1b custom config for DAM

# Type of ec2 to use for testing
types:
  mongodb: m5.4xlarge
  nuxeo: c5.4xlarge
  nuxeospot: c5.4xlarge
  elastic: c5.9xlarge
  gatling: c5.2xlarge
  kafka: c5.xlarge
  monitor: c5.xlarge

# Number of nodes
counts:
  mongodb: 3
  nuxeo: 2
  nuxeospot: 0
  elastic: 1
  gatling: 1
  kafka: 1
  monitor: 1

# ebs volume size per disk per instance: total size for a group is: counts * volsizes * raid0
volsizes:
  mongodb: 500
  elastic: 500
  kafka: 500
  nuxeo: 50
  nuxeospot: 50    # 1 disk
  gatling: 40
  monitor: 50

voltypes:
  mongodb: io1
  elastic: io1
  kafka: gp2
  nuxeo: gp2
  nuxeospot: gp2
  gatling: gp2
  monitor: io1

# number of ebs disk to aggregate in raid0
raid0:
  mongodb: 2
  elastic: 4
  kafka: 2
  nuxeo: 2
  nuxeospot: 1
  gatling: 1
  monitor: 2

# To use spot instance set a price
spot_price:
  nuxeospot: "0.3"

#iops: 2000
iops: 2000

# Mass Import configuration with nuxeo-platform-importer
impnbThreads: 20
impnbNodes:  10000000
impnbBlobs:     10000
impBlobsSizeKB:  1
impbatchSize: 10


#impnbThreads: 20
#impnbNodes:   100000
#impnbBlobs:     1000
#impBlobsSizeKB:  1
#impbatchSize: 10

# Test
#impnbThreads: 2
#impnbNodes:  500
#impnbBlobs:    100
#impBlobsSizeKB: 1
#impbatchSize: 10


