---
# Setup mongos router

- name: Check if mongos is already setup
  stat: path=/etc/init/mongos.conf
  register: sts

- name: Install mongos
  apt: state=latest name={{item}} force=yes
  with_items:
  - mongodb-org-mongos
  when: not sts.stat.exists

- user: name=mongodb

- name: Create mongo log dir
  file: path=/ssd/mongo-log state=directory owner=mongodb

- name: Set mongos configuration file
  template: src=mongos.conf.j2 dest=/etc/mongos.conf

- name: Set mongos upstart file
  template: src=mongos.j2 dest=/etc/init/mongos.conf

- name: Restart mongos
  service: name=mongos state=restarted
  when: not sts.stat.exists

- name: Ensure mongos started
  service: name=mongos state=started
  when: sts.stat.exists

- name: Link mongos log
  file: path=/var/log/mongos.log
        src=/ssd/mongo-log/mongos.log
        state=link
        force=yes

- name: Create mongos shard init script
  template: src=add_shards.j2 dest=/tmp/add_shards.js

- name: Add shards to cluster
  run_once: true
  shell: /usr/bin/mongo --host {{ private_ip }} --port 27017 /tmp/add_shards.js
  when: not sts.stat.exists